FROM node:22-bullseye-slim

RUN apt-get update \
    && apt-get install -y dnsutils build-essential procps python3 \
    chromium fonts-noto  \
    && apt-get clean

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

ENV PNPM_HOME="/pnpm"

ENV PATH="$PNPM_HOME:$PATH"

RUN npm i -g pnpm 

RUN pnpm config set auto-install-peers true

WORKDIR /app

COPY package.json /app

COPY pnpm-lock.yaml /app

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm i 


